apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-webapp
  name: portfolio-tier
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: portfolio-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio-webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-webapp
  template:
    metadata:
      labels:
        app: portfolio-webapp
    spec:
      containers:
        - name: portfolio-webapp
          image: ghcr.io/dokokitsune/ts-next-portfolio:v1.0.3 # {"$imagepolicy": "flux-system:portfolio-webapp"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
