---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: portfolio-webapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: portfolio-webapp
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical:
      order: asc
