---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: portfolio-webapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: portfolio-webapp
  policy:
    semver:
      range: ">=0.1.0"
