---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: portfolio-webapp
  namespace: flux-system
spec:
  image: ghcr.io/dokokitsune/ts-next-portfolio
  interval: 5m0s
